### ISSUE TITLE
Exclusion of `||mkto-*.com^`  does not work

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HostlistCompiler#14]
https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/0af7ac8a76811b9f9fdd1a03cb01b6e85e4e22da#diff-acd17ea33c2f5734c4ad29ee78791c6a475ad226211abde67e8167ce320f808dR2
![image](https://user-images.githubusercontent.com/8361299/117810449-1397f200-b268-11eb-899e-01e85c541d4e.png)

**Comment by ameshkov** [comment]
The problem is that when `*` is used in exclusion, it is parsed as a wildcard (i.e. transformed into a regex like this: `^\|\|mkto-[\s\S]*\.com\^$`).

The simple way to fix this would be to change exclusion to a regular expression: https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/01411170e1f4d447cb143423c08b29d83f418771
