### ISSUE TITLE
Adblock exclusions doesn't work for hosts lists

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/HostlistCompiler#46]
Hello,

for example, I have this list in hosts format:
https://blocklistproject.github.io/Lists/ads.txt
there is blocking rule `0.0.0.0 joyreactor.cc`👆🏼

Also I have the exclusions list:
https://github.com/ammnt/DeadEnd/blob/main/exclusions.txt
there is the rule `||joyreactor.cc^`👆🏼

As result the blocking rule is not excluded🤷🏻‍♂️ I need another exclusion rule in the same format or what?🤔

The full configuration here:
https://github.com/ammnt/DeadEnd/blob/main/configuration.json

Thanks!

**Comment by ameshkov** [comment]
That's right, you need another exclusion for that. Exclusions are simple strings or regular expressions that are checked against every line.

**Comment by hagezi** [comment]
@ameshkov But the following exclusion should work because it is done after conversion to Adblock format, or do I have a knot in my brain?
https://github.com/ammnt/DeadEnd/blob/2e45457054f3b4e41ac324e6859d8437a328210a/configuration.json#L164

`0.0.0.0 joyreactor.cc` converted to `||joyreactor.cc^` and at the end excluded by `||joyreactor.cc^`

**Comment by ammnt** [comment]
Yeah, I thought that, too. But it doesn't work🤨

**Comment by ammnt** [comment]
@ameshkov, can we reopen and convert this task to feature please?🙂 Thank you.

**Comment by ameshkov** [comment]
The problem here is that exclusions are applied **before** transformations.

Please try adding `Compress` transformation to every source and check if it changes anything.

**Comment by ammnt** [comment]
@ameshkov, yes! It works as expected now! But need more test of course... Thank you so much😊
