### ISSUE TITLE
Allow using the rules with IP, not just hostname

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HostlistCompiler#69]
Some rules are available in DNS filters
```
||213.8.137.51^
||167.71.252.38^
```

but the most are rejected, like
```
» invalid hostname 185.149.120.173 in the rule: ||185.149.120.173^
```

These rules can be used in AdGuard Private DNS, and should not be rejected:

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/6d4a7d4e-1935-4b25-9fc8-eaff9ece3efd)

</details>

**Comment by DandelionSprout** [comment]
From what I can remember, I've strongly recommended adding more IP-based entries in AdGuard DNS Filter for some time, and I've considered it as *very* critical to support in order to help accomplish more wildcarding in AdGuard DNS Filter.

Based on https://filters.adtidy.org/windows/filters/2.txt, I could find 164 entries that should strongly be considered converting and adding to AdGuard DNS Filter:

<details><summary>The entries:</summary>

```
57.128.71.215$network
91.204.226.224$network
139.45.197.151$network
139.45.197.152$network
139.45.197.153$network
139.45.197.154$network
157.90.183.248$network
167.71.252.38$all
185.149.120.173$network
185.246.188.124$network
185.246.188.125$network
188.72.219.36^$network
193.200.64.30$network
193.200.64.31$network
193.200.65.61$network
194.63.140.103$network
194.63.143.61$network
194.63.143.96$network
212.117.190.201$network
212.117.190.202$network
212.117.190.210$network
212.117.190.211$network
212.117.190.212$network
212.117.190.213$network
||23.109.150.101^$popup
||23.109.150.208^
||23.109.150.253^
||23.109.170.212^
||23.109.170.228^
||23.109.248.125^
||23.109.248.129^
||23.109.248.130^
||23.109.248.135^
||23.109.248.139^
||23.109.248.149^
||23.109.248.14^
||23.109.248.174^
||23.109.248.183^
||23.109.248.20^
||23.109.248.229^
||23.109.248.247^
||23.109.248.29^
||23.109.82.104^$popup
||23.109.82.119^$popup
||23.109.82.173^$popup
||23.109.82.222^$popup
||23.109.82.44^$popup
||23.109.82.74^$popup
||23.109.87.101^$popup
||23.109.87.118^$popup
||23.109.87.123^
||23.109.87.127^$popup
||23.109.87.139^$popup
||23.109.87.14^$popup
||23.109.87.15^$popup
||23.109.87.182^$popup
||23.109.87.192^$popup
||23.109.87.213^$popup
||23.109.87.217^$popup
||23.109.87.42^$popup
||23.109.87.47^$popup
||23.109.87.71^$popup
||23.109.87.74^$popup
||23.195.91.195^
||34.102.137.201^
||37.1.209.213^
||37.1.213.100^$all
||5.45.79.15^$popup
||5.61.55.143^$all
||51.178.195.171^$popup
||51.195.115.102^$popup
||51.77.227.100^
||51.77.227.101^
||51.77.227.102^
||51.77.227.103^
||51.77.227.96^
||51.77.227.97^
||51.77.227.98^
||51.77.227.99^
||51.89.115.13^$popup
||51.89.187.136^
||51.89.187.137^
||51.89.187.138^
||51.89.187.139^
||51.89.187.140^
||51.89.187.141^
||51.89.187.142^
||51.89.187.143^
||88.42.84.136^
||109.123.233.251^
||141.98.82.232^
||142.91.159.107^$popup
||142.91.159.127^$popup
||142.91.159.136^$popup
||142.91.159.139^$popup
||142.91.159.146^$popup
||142.91.159.147^$popup
||142.91.159.164^$popup
||142.91.159.169^$popup
||142.91.159.179^$popup
||142.91.159.220^$popup
||142.91.159.223^$popup
||142.91.159.244^$popup
||143.244.184.39^$popup
||146.59.223.83^$popup
||158.247.208.115^$popup
||162.252.214.4^
||167.206.10.148^
||167.99.31.227^
||172.255.103.118^
||172.255.103.171^$popup
||172.255.6.135^
||172.255.6.137^
||172.255.6.139^
||172.255.6.140^
||172.255.6.150^
||172.255.6.152^
||172.255.6.199^
||172.255.6.217^
||172.255.6.228^
||172.255.6.248^
||172.255.6.252^
||172.255.6.254^
||172.255.6.2^
||172.255.6.59^
||176.31.68.242^$popup
||185.147.34.126^$popup
||185.149.120.173^
||188.42.84.110^
||188.42.84.137^
||188.42.84.159^
||188.42.84.160^
||188.42.84.162^
||188.42.84.199^$popup
||188.42.84.21^
||188.42.84.23^
||188.72.219.36^
||203.195.121.0^
||203.195.121.103^
||203.195.121.119^
||203.195.121.11^
||203.195.121.134^
||203.195.121.184^
||203.195.121.195^
||203.195.121.1^
||203.195.121.209^
||203.195.121.217^
||203.195.121.219^
||203.195.121.224^
||203.195.121.229^
||203.195.121.24^
||203.195.121.28^
||203.195.121.29^
||203.195.121.34^
||203.195.121.36^
||203.195.121.40^
||203.195.121.46^
||203.195.121.70^
||203.195.121.72^
||203.195.121.73^
||203.195.121.74^
/139.45.197.24\d/$network
/^139\.45\.19[5-7]\.\d{1,3}/$network
/^188\.42\.84\.\d{1,3}/$network
/^23\.109\.170\.(18[7-9]|19[0-2])$/$network
/^23\.109\.73\.\d{3}/$network
```

</details>

Handling `$network` would presumably be as easy as adding `modified = ruleUtils.removeModifier(props, 'network') || modified;` to https://github.com/AdguardTeam/HostlistCompiler/blob/master/src/transformations/remove-modifiers.js. If I was to have done a PR for it, I can only desperately hope that it won't get closed by Meshkov who think AGH lists should be made for AGH by scratch, a reasoning that makes practically no sense in regards to `$network`.

`||(IP address)^` I unfortunately can't figure out how to add support for.

**Comment by ameshkov** [comment]
Allowing IP addresses is rather dangerous tbh. For instance, you can specify an IP address that's actually shared among tons of different websites.

One solution would probably be to have a blacklist of IP ranges that are not allowed: Cloudflare, Akamai, Fastly, Google, etc. But is it a good enough protection?

**Comment by DandelionSprout** [comment]
The way I see it, is that the IPs to be blocked in regards to AdGuard DNS Filter, are those that have already been blocked by the regular (non-DNS) blocking modes of AdGuard for Windows/Android/Mac, in some cases for years.

So, why would those IPs be perfectly okay in AdGuard Base Filter for Windows/Android, but that the exact same IPs would not be okay in AdGuard DNS Filter for Windows/Android/Mac/Public DNS/AGH?

If anything, almost all of those entries would've been tested in deep detail by now, in the sense that there's not a whole lot of reports in the "Filters Registry" repo that has brought up issues relating to those IPs being blocked.

**Comment by Alex-302** [comment]
What about trust levels like in FiltersRegistry?

### Trust levels

* `full` - allowed any rules for blocking websites by IP - exact or partial IP address and regexp rules. In Adblock-style rules, a minimum of the first two octets must be specified, because such rules are not flexible enough. Regexp rules can be used to block IPs by all octets. Applied to `AdGuard DNS filter` and user rules of AdGuard Private DNS.

  **Examples:**
  * `||1.2.3.4` - matches the exact IP address;
  * `||1.2.*.*` - matches the IP range `1.2.0.1-1.2.255.254`;
  * `/^1\.\d{1,3}\.3\.2(4[0-9]|5[0-4])$/` - matches the IP range `1.0.3.240-1.255.3.254`;
  
* `high` - allowed Adblock-style rules for blocking websites by IP addresses, where the first three octets are specified without wildcards. Regexp rules can be used to block sites by the last two octets of IP address. Applied to trusted filters.

  **Examples:**
  * `1.2.3.4` - matches the exact IP address;
  * `1.2.3.` / `1.2.3.*` - matches the IP range `1.2.3.1-1.2.3.254`;
  * `/^1\.2\.[3-4]\.100$/` - matches the IPs `1.2.3.100` and `1.2.4.100`;

* `low` - only a specific IP address is allowed. Wildcards and regexp in rules are forbidden. Ddefault level for third-party filters in Adblock-style rules.

  **Examples:**
  * `1.2.3.4` - matches the exact IP address.

**Comment by ameshkov** [comment]
Compiler is a more low-level tool.

Currently, IP addresses are discarded by [`Validate`](https://github.com/AdguardTeam/HostlistCompiler?tab=readme-ov-file#-validate).

We could add `ValidateAllowIP` that will be a more relaxed version of `Validate` and then you can use it for the lists that you trust.

**Comment by DandelionSprout** [comment]
Since the entries and IPs in question are into AdGuard's lists (primarily AdGuard DNS Filter), trust levels would've been a different topic altogether.

From how I understand [Validate.js](https://github.com/AdguardTeam/HostlistCompiler/blob/master/src/transformations/validate.js), it seems it's its reliance on the `tldts` dependency that is causing IP addresses to be discarded. Since `tldts` is maintained by someone else than Team AdGuard, I take an unqualified guess that the dependency would have to be removed in its entirety from Validate.js.

Though checking https://github.com/AdguardTeam/HostlistCompiler/blob/3e9d4c814f22c33834d2566890274978010ba13d/src/transformations/validate.js#L38-L41, I presume that allowing IP addresses would be as simple as removing that paragraph. Or at least I hope it does.
